# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ad7a689d404c9270c7cf421e836fda98b20b9f66cd75ae353c8b2a73adde1eb89a1e2e70ad80c065672fc886868dff7da7256018996da5dd7ae55c3259a5bca9

test:
  secret_key_base: 11bc7409c1a35ae1822df34ff18912341bed45b98dd002c718a595a744028ae6b5538933c30023ef88150a1aaa4c2c06800836aa57d90f73b66fe86458b4a53b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
